host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: ps-is-ifd
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - harshad16
        - pacospace
        - eldritchjs
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
  - name: thoth-advise
    configuration:
      labels: [bot]
